schema_version = "1.0.0"

id = "io_images"
version = "1.0.0"
name = "Export All Images"
tagline = "Saves all images to a directory"
maintainer = "Rodrigo Hernandez <contact@email.com>"
type = "add-on"

tags = ["Import-Export", "Image"]

blender_version_min = "5.0.0"

license = ["SPDX:Apache-2.0"]

website = "https://github.com/AeonGames/AeonEngine"
